version: '3.5'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: aiesecmx_web
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
  
  wp:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      WP_ENV: local
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: aiesecmx_web
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_TABLE_PREFIX: aiesec_

volumes:
  mysql-volume: